#!/usr/bin/env python3
"""Generate src/imports.inc from Wine's .spec files.

The only thing we take from Wine here is interface data - ordinal numbers, API
names, argument sizes and return conventions - which is ABI fact, not code.

Usage:  python tools/genimports.py [path-to-wine-tree] > src/imports.inc
"""
import os
import re
import sys

# This writes src/imports.inc through a shell redirect, and Python's text-mode
# stdout on Windows turns every \n into \r\n.  That is how that file - and only
# that file, of everything generated here - came to be CRLF in a tree that is
# otherwise LF.  Ask for LF explicitly instead.
sys.stdout.reconfigure(newline="\n")

WINE = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/src/wine")

# The exact ordinals stars.exe references, recovered from its relocation
# records.  Keeping the list explicit means an unexpected import shows up as a
# build-time gap rather than a silent runtime stub.
WANTED = {
    "KERNEL": (
        "krnl386.exe16/krnl386.exe16.spec",
        [1, 3, 5, 6, 7, 10, 15, 16, 17, 18, 19, 20, 23, 24, 29, 30, 49, 51, 52,
         60, 61, 62, 63, 64, 65, 66, 74, 81, 82, 86, 88, 89, 90, 91, 102, 113,
         114, 127, 128, 129, 131, 136, 137, 178],
    ),
    "GDI": (
        "gdi.exe16/gdi.exe16.spec",
        [1, 2, 4, 9, 11, 19, 20, 21, 22, 24, 27, 29, 31, 33, 34, 38, 44, 45, 51,
         52, 57, 60, 61, 64, 66, 68, 69, 75, 80, 82, 85, 87, 91, 93, 128, 148,
         150, 351, 360, 439, 441],
    ),
    "USER": (
        "user.exe16/user.exe16.spec",
        [1, 5, 6, 7, 10, 12, 13, 15, 17, 18, 19, 22, 23, 28, 29, 30, 31, 32, 33,
         34, 36, 37, 39, 40, 41, 42, 46, 49, 53, 56, 57, 60, 61, 62, 63, 64, 66,
         68, 69, 72, 74, 76, 77, 78, 79, 81, 83, 84, 85, 87, 88, 89, 91, 92, 93,
         96, 97, 98, 101, 104, 105, 106, 107, 108, 109, 110, 111, 113, 114, 122,
         124, 125, 127, 135, 136, 152, 154, 155, 157, 159, 160, 171, 173, 174,
         175, 177, 178, 179, 180, 232, 244, 249, 258, 262, 263, 272, 282, 283,
         370, 410, 411, 413, 415, 416, 420, 457, 458],
    ),
    "COMMDLG":  ("commdlg.dll16/commdlg.dll16.spec",  [1, 2, 20]),
    "TOOLHELP": ("toolhelp.dll16/toolhelp.dll16.spec", [80]),
    "MMSYSTEM": ("mmsystem.dll16/mmsystem.dll16.spec", [701]),
    "WIN87EM":  ("win87em.dll16/win87em.dll16.spec",   [1]),
}

# WAVEMIX has no Wine .spec.  Names come from wavemix.dll's own non-resident
# name table, and every pop count below was read out of the DLL itself: each
# export ends in RETF imm16, and that immediate IS the Pascal pop count.  See
# tools/checkwavemix.sh, which re-derives them.
WAVEMIX = [
    (4,  "WaveMixActivate",      4),
    (5,  "WaveMixOpenWave",     12),
    (6,  "WaveMixOpenChannel",   8),
    (7,  "WaveMixPlay",          4),
    (8,  "WaveMixFlushChannel",  8),
    (9,  "WaveMixCloseChannel",  8),
    (10, "WaveMixFreeWave",      6),
    (11, "WaveMixCloseSession",  2),
    (12, "WaveMixPump",          0),
    (14, "WaveMixGetInfo",       4),
    (15, "WaveMixConfigureInit", 4),
]

ARGSIZE = {
    "word": 2, "s_word": 2, "long": 4, "ptr": 4, "str": 4, "wstr": 4,
    "segptr": 4, "segstr": 4, "float": 4, "int64": 8, "double": 8,
}

# A few entries Wine declares as `stub`, so its spec carries no signature.
OVERRIDE_POP = {
    ("KERNEL", 1): 2,      # FatalExit(WORD)
}


def parse(path, ordinals):
    by = {}
    with open(path) as fh:
        for line in fh:
            s = line.split("#")[0].strip()
            if not s:
                continue
            m = re.match(r"^(\d+)\s+(\S+)(.*)$", s)
            if m:
                by[int(m.group(1))] = s

    out = []
    for o in ordinals:
        s = by.get(o)
        if s is None:
            raise SystemExit("ordinal %d not found in %s" % (o, path))

        equate = re.match(r"^\d+\s+equate\s+(\S+)\s+(\S+)", s)
        if equate:
            out.append((o, equate.group(1), 0, "IMP_EQUATE",
                        int(equate.group(2), 0)))
            continue

        name = re.match(r"^\d+\s+\S+\s+(?:-\S+\s+)*([A-Za-z_][A-Za-z0-9_]*)", s)
        name = name.group(1)
        args = re.search(r"\(([^)]*)\)", s)
        args = args.group(1).split() if args else []

        pop = 0
        for a in args:
            if a not in ARGSIZE:
                raise SystemExit("unknown arg type %r in: %s" % (a, s))
            pop += ARGSIZE[a]

        flags = []
        if "-ret16" not in s:
            flags.append("IMP_RET32")
        if "-register" in s:
            flags.append("IMP_REGISTER")
        if re.match(r"^\d+\s+(cdecl|varargs)", s):
            flags.append("IMP_CDECL")
            pop = 0                       # caller cleans up
        out.append((o, name.lstrip("_"), pop, " | ".join(flags) or "0", None))
    return out


def main():
    print("/* Generated by tools/genimports.py - do not edit by hand.")
    print(" *")
    print(" * IMP(module, ordinal, name, pop_bytes, flags)")
    print(" * EQU(module, ordinal, name, value)")
    print(" *")
    print(" * pop_bytes is what the callee removes under the Pascal convention;")
    print(" * it is 0 for cdecl entries, where the caller cleans up instead.")
    print(" */")
    total = 0
    for mod in ("WIN87EM", "KERNEL", "GDI", "USER", "COMMDLG",
                "TOOLHELP", "WAVEMIX", "MMSYSTEM"):
        print("")
        print("MODULE(%s)" % mod)
        if mod == "WAVEMIX":
            for o, name, pop in WAVEMIX:
                print('IMP(%s, %d, "%s", %d, IMP_RET32)' % (mod, o, name, pop))
                total += 1
            continue
        spec, ordinals = WANTED[mod]
        for o, name, pop, flags, value in parse(os.path.join(WINE, "dlls", spec),
                                                ordinals):
            pop = OVERRIDE_POP.get((mod, o), pop)
            if value is not None:
                print('EQU(%s, %d, "%s", 0x%X)' % (mod, o, name, value))
            else:
                print('IMP(%s, %d, "%s", %d, %s)' % (mod, o, name, pop, flags))
            total += 1
    print("")
    print("/* %d imports total */" % total)


main()
